### ISSUE TITLE
What are the differences between the P4-DPDK Target and BMv2? 

### ISSUE THREAD

**Issue by justinkong0623** [p4lang/p4-dpdk-target#109]
The biggest difference here lies in whether the former utilizes DPDK, or are there other distinctions as well?

**Comment by jafingerhut** [comment]
If you do not mind, I would recommend asking this question in the public web forum https://forum.p4.org, because such questions are a searchable resource for such questions (and often answers, too).

**Comment by jafingerhut** [comment]
I would recommend closing this issue (I do not have permission to do so on this repo), as it is discussed here: https://forum.p4.org/t/what-are-the-differences-between-the-p4-dpdk-target-and-bmv2/951
