### ISSUE TITLE
DPDK eal-args parsing does not work

### ISSUE THREAD

**Issue by lzhzero** [p4lang/p4-dpdk-target#15]
In the config file example and README.md, the `eal-args` for DPDK is member of `p4_programs`.
https://github.com/p4lang/p4-dpdk-target/blob/main/bf_switchd/bfrt_dpdk_sample_config.conf#L18

However in the program, `eal-args` is member of `p4_device` instead.
https://github.com/p4lang/p4-dpdk-target/blob/main/bf_switchd/lib/bf_switchd_lib_init.h#L80

This caused eal-args parsing no working.

**Comment by nisbhat** [comment]
This issue has been identified and resolved internally. Should reflect here shortly.
Please modify eal-args as follows :

{
    "chip_list": [
        {
            "id": "asic-0",
            "chip_family": "dpdk",
            "instance": 0,
        }
    ],
    "instance": 0,
    "p4_devices": [
        {
            "device-id": 0,
            "eal-args": "dummy -n 4 -c 3",
            "p4_programs": [
                {

                }
            ],
        }
    ]
}
