### ISSUE TITLE
Does this DPDK target works for PNA programs?

### ISSUE THREAD

**Issue by lzhzero** [p4lang/p4-dpdk-target#16]
p4c-dpdk can compile PNA programs into spec files. When I try to load it into the bf_switchd target, and run `bfrt.<program_name>.enable`, I get "Invalid struct field size." error.
I think this is related to some of the PNA metadata fields are 3 bits like `bit<3> pna_pre_input_metadata_pass`

However, when I hack the .spec file to make them `bit<8>`, I got "Pipeline build error."

Could you supply some sample programs that can load and run on this DPDK target? Maybe the l3_simple_demo example that is mentioned in the `tools` folder.

**Comment by TingtingXuA** [comment]
Exactly the same question, hope for an answer!

**Comment by jamescchoi** [comment]
We will add an PNA P4 example and include the steps to build and run.

**Comment by lzhzero** [comment]
Thanks for the link and explanation.
I am able to run the simple_l3.p4 PSA program and add table entries using the bfrt_python shell of the `bf_switchd` binary.

So far, I can't load table entries using the `bfshell` binary. Do I need the  `p4testutils` python package? If so, do you plan to make it available?

**Comment by akaevgen** [comment]
> We will add an PNA P4 example and include the steps to build and run.

Hi James, 

Could you pls update the status and clarify will PNA arch supported?

Thanks in advance.

**Comment by swaroopsarma** [comment]
Yes it works for PNA programs as well and you can find some in examples/pna.
As @akaevgen  points out ,  this is a limitation from the backend
