### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by MatthewTromp** [p4lang/p4-dpdk-target#44]
The link given for P4-OVS ([https://github.com/ipdk-io/p4-ovs](https://github.com/ipdk-io/p4-ovs)) is dead. It should probably be [https://github.com/osinstom/P4-OvS](https://github.com/osinstom/P4-OvS)

**Comment by rst0git** [comment]
The correct link is https://github.com/ipdk-io/ovs

**Comment by swaroopsarma** [comment]
already addressed
