### ISSUE TITLE
Problem binding physical NIC in bf_switchd.

### ISSUE THREAD

**Issue by PLizolan** [p4lang/p4-dpdk-target#54]
Hello,
Has anyone gone through the situation I'm going through to link a physical NIC to p4-dpdk-target .
I already have no idea what to do to successfully execute the binding.
The problem only occurs when using BFRT, I tested it with the DPDK examples and the card links normally.
The error that appears when trying to attach the physical card to bf_switchd is how it cannot read the ports.json file, but this only happens with physical cards.

Log syslog.
Oct 19 23:48:13 master-node dummy[942929]: EAL: Probe PCI driver: net_nfp_pf (19ee:4000) device: 0000:41:00.0 (socket 1)
Oct 19 23:48:13 master-node kernel: [34440.907257] igb_uio 0000:41:00.0: uio device registered with irq 87
MInha dúvida ao efetuar os teste descritos é:Oct 19 23:58:07 master-node dummy[957429]: 2022-10-19 23:58:07.648645 ERROR  (BF_PORT:(file=null):(func=null):0) - port_config_json_parse_ports:507: Failed to add port LINK0
Oct 19 23:59:07 master-node dummy[957429]: 2022-10-19 23:58:07.648667 ERROR  (BF_PORT:(file=null):(func=null):0) - parse_port_config_json:586: Failed to parse ports from Port Config JSON
Oct 19 23:59:07 master-node dummy[957429]: 2022-10-19 23:58:07.648705 ERROR  (BF_PORT:(file=null):(func=null):0) - port_mgr_config_import : Error in parsing the port config file
Oct 19 23:59:07 master-node dummy[957429]: 2022-10-19 23:58:07.648744 ERROR  (BF_DVM:(file=null):(func=null):0) - Device add handling failed for dev 0, sts No system resources (2), Client port_mgr
Oct 19 23:59:07 master-node dummy[957429]: 2022-10-19 23:58:07.648764 ERROR  (BF_DVM:(file=null):(func=null):0) - Device add failed for dev 0, sts No system resources (2)

Log bfshell
LINK CREATE: Dev:0000:41:00.0 Args: dev_hotplug_enabled: 0
2022-10-19 09:54:00.196125 BF_LLD ERROR - Creation of Link Port LINK0 failed

2022-10-19 09:54:00.196285 BF_PORT ERROR - port_config_json_parse_ports:507: Failed to add port LINK0
2022-10-19 09:54:00.196322 BF_PORT ERROR - parse_port_config_json:586: Failed to parse ports from Port Config JSON
2022-10-19 09:54:00.196377 BF_PORT ERROR - port_mgr_config_import : Error in parsing the port config file
2022-10-19 09:54:00.196436 BF_DVM ERROR - Device add handling failed for dev 0, sts No system resources (2), Client port_mgr
2022-10-19 09:54:00.196466 BF_DVM ERROR - Device add failed for dev 0, sts No system resources (2)
ERROR: bf_device_add failed(2) for dev_id 0
ERROR: bf_switchd_device_add failed(2) for dev_id 0

bf_switchd: initialized 0 devices
bf_switchd_switchsai_lib_init
 starting SAI
bf_switchd: spawning cli server thread
bf_switchd: spawning driver shell
bf_switchd: server started - listening on port 9999

        ********************************************
        *      WARNING: Authorised Access Only     *
        ********************************************

Every help is welcome,
Thanks.

**Comment by stolsma** [comment]
Your port config json file is mot correct...

> 2022-10-19 23:58:07.648667 ERROR (BF_PORT:(file=null):(func=null):0) - parse_port_config_json:586: Failed to parse ports from Port Config JSON

**Comment by PLizolan** [comment]
> Your port config json file is not correct...
> 
> > 2022-10-19 23:58:07.648667 ERROR (BF_PORT:(file=null):(func=null):0) - parse_port_config_json:586: Failed to parse ports from Port Config JSON
> 
> And I'm not sure but I thought bfrt is the version for physical Tofino chip based ethernet switches so you can't connect your nic card to that switch in software...
> 
> > The problem only occurs when using BFRT, I tested it with the DPDK examples and the card links normally.
> 
> The DPDK version is using DPDK SWX code as the dataplane switch and as such you can connect your local nic to it...
> 
> But it could be I didn't understand your setup...

Hey,
Thank you for your comment, and you are right in your speech, it ended up that I mistakenly explained my problem citing the BFRT, where the right thing is to run the switch with the DPDK SWX.
But with that, a question arises, would there be a way to check if when running bf_switchthd it is loading/finding the necessary files for it to run the DPDK SWX?
Please note that p4-dpdk-target was installed following the steps of the github repository.

Sincerely thank you.

**Comment by stolsma** [comment]
> But with that, a question arises, would there be a way to check if when running bf_switchthd it is loading/finding the necessary files for it to run the DPDK SWX?

As far as I know the code in this repo compiles to a program destined to work for DPDK SWX and as such you always know... 😏

If you want the code to support Tofino network chip family you need to compile with the Intel/Barefoot SDE (Software Development Environment) and for that you need to sign a NDA with Intel...
