### ISSUE TITLE
DPDK and TAP interface MTU differ, leading to packet truncation

### ISSUE THREAD

**Issue by pudelkoM** [p4lang/p4-dpdk-target#62]
The DPDK port and Linux TAP interface are configured with the same MTU value when calling `lld_dpdk_pipeline_tap_port_add`.

This causes a truncation problem at runtime, that stems from fact that this MTU is understood differently by DPDK and Linux:

### [Linux](https://www.kernel.org/doc/html/v5.8/networking/netdevices.html):

> Each network device has a Maximum Transfer Unit. The MTU does not
> include any link layer protocol overhead. Upper layer protocols must
> not pass a socket buffer (skb) to a device to transmit with more data
> than the mtu. The MTU does not include link layer header overhead, so
> for example on Ethernet if the standard MTU is 1500 bytes used, the
> actual skb will contain up to 1514 bytes because of the Ethernet
> header. Devices should allow for the 4 byte VLAN header as well.

### DPDK:

DPDK treats the MTU as the memory buffer (mbuf) size including ALL headers. This includes Ethernet (14) and the FCS CRC checksum (4).

In my understanding, this means the TAP interface will accept frames that too large for DPDK and thus will get truncated. 

### Suggestion

I think the TAP interface configuration should happen with MTU-18 to unify behavior: https://github.com/p4lang/p4-dpdk-target/blob/5eb0ff3b6fd996986abec6e380f51fe0018fe194/src/lld/dpdk/lld_dpdk_port.c#L106

_Note: 14 bytes seems to work too, I think we're just cutting off the FCS then. Maybe some DPDK expert can chime in here?_

This lower TAP MTU should cause Linux to send an ICMP error back to the sender, hopefully triggering [Path MTU discovery](https://en.wikipedia.org/wiki/Path_MTU_Discovery) there.

### Workaround

Until this is fixed in the SDE, there is a hacky workaround in the interim: 
If you can ensure that there is never a Ethernet frame larger than the DPDK MTU, this issue will not occur. Either
 - Set the DPDK MTU to your Linux interface MTU + 18
or
 - Decrease the Linux interface MTU by 18: `ip l set mtu 1400 dev h1-eth0`

By Linux interface I mean regular, other IP hosts in the network, **NOT** the DPDK TAP interfaces!

### Example pcap with the truncation issue
```pcap
20:17:55.196347 a6:c0:aa:27:c8:2b > 00:00:00:00:03:14, ethertype IPv4 (0x0800), length 1500: truncated-ip - 14 bytes missing! (tos 0x0, ttl 64, id 1, offset 0, flags [none], proto UDP (17), length 1500)
    10.0.0.1.53 > 10.0.0.2.53: 12336 op6% [12336a] [12336q] [12336n] [12336au][|domain]
```

**Comment by pudelkoM** [comment]
> Yep, can confirm this problem... Found this out the hard way yesterday when doing some performance & throughput tests with DPDK SWX....😢

Haha same here. iperf refused to run. I made it work by setting the host MTUs to DPDK_MTU-18 so that there are no too large Ethernet frames generated.

If you do get it to run, would you mind sharing your numbers? Here's my completely unscientific first run:

```
root@481195d7006c:~# iperf3 -c 10.0.0.2 -i1
Connecting to host 10.0.0.2, port 5201
[  7] local 10.0.0.1 port 59632 connected to 10.0.0.2 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  7]   0.00-1.00   sec  31.6 MBytes   265 Mbits/sec  425   17.9 KBytes
[  7]   1.00-2.00   sec  53.5 MBytes   448 Mbits/sec  364   17.9 KBytes
[  7]   2.00-3.00   sec  40.8 MBytes   343 Mbits/sec  337   20.2 KBytes
[  7]   3.00-4.00   sec  48.3 MBytes   405 Mbits/sec  369   17.9 KBytes
[  7]   4.00-5.00   sec  39.1 MBytes   328 Mbits/sec  346   16.8 KBytes
[  7]   5.00-6.00   sec  45.2 MBytes   380 Mbits/sec  393   19.1 KBytes
[  7]   6.00-7.00   sec  46.0 MBytes   386 Mbits/sec  350   17.9 KBytes
[  7]   7.00-8.00   sec  42.7 MBytes   358 Mbits/sec  305   19.1 KBytes
[  7]   8.00-9.00   sec  42.0 MBytes   352 Mbits/sec  337   24.7 KBytes
[  7]   9.00-10.00  sec  47.8 MBytes   401 Mbits/sec  379   19.1 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  7]   0.00-10.00  sec   437 MBytes   367 Mbits/sec  3605             sender
[  7]   0.00-10.05  sec   437 MBytes   365 Mbits/sec                  receiver
iperf Done.
```

**Comment by stolsma** [comment]
Sorry I didn't mention that I'm in my spare time working on a [Golang DPDK SWX package](https://github.com/stolsma/go-p4pack). As example code flows I'm using the P4-DPDK-Target and the DPDK Pipeline example code. With that I created a bare bones demo vswitch app and when I was finally ready to do a real packet switching test I saw that iperf didn't work, and yes, I found out I copied the same "bug" 😄

As the Dataplane is the same (DPDK SWX with the example C thread code) we could do some number sharing I think! 👍 

On my Windows 8 core (Processor: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (8 phy. core 16 log. core)), WSL2 based dev environment (with Linux netns demo with tap-to-tap traffic) my run looks like:

```
sander@xxxxxxxx:~$ sudo ip netns exec host2 iperf3 -c 192.168.222.1
Connecting to host 192.168.222.1, port 5201
[  5] local 192.168.222.2 port 47182 connected to 192.168.222.1 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   190 MBytes  1.59 Gbits/sec   46   1.13 MBytes       
[  5]   1.00-2.00   sec   198 MBytes  1.66 Gbits/sec    0   1.25 MBytes       
[  5]   2.00-3.00   sec   191 MBytes  1.60 Gbits/sec    0   1.35 MBytes       
[  5]   3.00-4.00   sec   196 MBytes  1.65 Gbits/sec    2   1.07 MBytes       
[  5]   4.00-5.00   sec   190 MBytes  1.59 Gbits/sec    0   1.19 MBytes       
[  5]   5.00-6.00   sec   198 MBytes  1.66 Gbits/sec    0   1.31 MBytes       
[  5]   6.00-7.00   sec   188 MBytes  1.57 Gbits/sec    1   1.01 MBytes       
[  5]   7.00-8.00   sec   194 MBytes  1.63 Gbits/sec    0   1.13 MBytes       
[  5]   8.00-9.00   sec   189 MBytes  1.58 Gbits/sec    0   1.25 MBytes       
[  5]   9.00-10.00  sec   194 MBytes  1.63 Gbits/sec    0   1.36 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  1.88 GBytes  1.62 Gbits/sec   49             sender
[  5]   0.00-10.01  sec  1.88 GBytes  1.61 Gbits/sec                  receiver

iperf Done.
```

Looks somewhat faster but that could be because of using TAP instead of physical interfaces. It will take me another week to setup a physical testbed (that is on the todo list). I also did a test with 10 flows and that gives me around 2 Gbits/sec consistently.

Let me know if you need some more data/info!!

**Comment by pudelkoM** [comment]
Very cool, thanks for sharing!
One thing I'd like to learn more about is the multi-core scaling opportunities with P4-DPDK.
@stolsma 
Should we open a new issue to collect findings about performance? Like setups, results, p4 programs?

**Comment by stolsma** [comment]
Hi @pudelkoM  Sorry for not replying sooner (too busy 😢 ) but I extended my test setup and implemented also the use of DPDK Virtio-user PMD interfaces (with `hotplug devargs: "path=/dev/vhost-net,queues=1,queue_size=32,iface=<pick your name>"` and this where the iperf3 results with the same setup as in my earlier reply (so virtio-net instead of tap interfaces on my Windows WSL2 dev environment).

```
sander@TTCNB004:~/develop/dpdk-pipeline$ sudo ip netns exec host4 iperf3 -c 192.168.222.3
Connecting to host 192.168.222.3, port 5201
[  5] local 192.168.222.4 port 59530 connected to 192.168.222.3 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   804 MBytes  6.74 Gbits/sec   38   1.18 MBytes       
[  5]   1.00-2.00   sec   790 MBytes  6.63 Gbits/sec    9   1.17 MBytes       
[  5]   2.00-3.00   sec   799 MBytes  6.70 Gbits/sec    1   1.38 MBytes       
[  5]   3.00-4.00   sec   788 MBytes  6.61 Gbits/sec   20   1.35 MBytes       
[  5]   4.00-5.00   sec   788 MBytes  6.61 Gbits/sec   17   1.41 MBytes       
[  5]   5.00-6.00   sec   798 MBytes  6.69 Gbits/sec   11   1.17 MBytes       
[  5]   6.00-7.00   sec   756 MBytes  6.34 Gbits/sec    1   1.17 MBytes       
[  5]   7.00-8.00   sec   784 MBytes  6.57 Gbits/sec   10   1.31 MBytes       
[  5]   8.00-9.00   sec   784 MBytes  6.57 Gbits/sec    2   1.37 MBytes       
[  5]   9.00-10.00  sec   776 MBytes  6.51 Gbits/sec    6   1.39 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  7.68 GBytes  6.60 Gbits/sec  115             sender
[  5]   0.00-10.00  sec  7.68 GBytes  6.60 Gbits/sec                  receiver

iperf Done.
```

So using virtio-user PMD already gives a 4x higher throughput compared to using tap/fd interfaces 😆  

Hopefully I can get my hardware lab up and running this week so I can do tests with real NICs. So yes, maybe it is better to open a new issue dedicated to performance etc... 😉

**Comment by pudelkoM** [comment]
Those are some impressive numbers!

**Comment by stolsma** [comment]
@pudelkoM I have my physical testbed (two supermicro servers with Intel(R) Xeon(R) CPU D-1518 @ 2.20GHz and 2x 10Gbit each interconnected back-to-back) up and running. What kind of tests do you have in mind?

BTW: 10gbit to 10gbit physical and then switched by the DPDK SWX pipeline to a virtio interface got:
```
[sander@sm1 go-p4pack]$ sudo ip netns exec host5 iperf -c 192.168.222.3 -P 10
------------------------------------------------------------
Client connecting to 192.168.222.3, TCP port 5001
TCP window size:  153 KByte (default)
------------------------------------------------------------
[ 12] local 192.168.222.4 port 53054 connected with 192.168.222.3 port 5001
[  5] local 192.168.222.4 port 53040 connected with 192.168.222.3 port 5001
[  4] local 192.168.222.4 port 53038 connected with 192.168.222.3 port 5001
[  3] local 192.168.222.4 port 53036 connected with 192.168.222.3 port 5001
[  6] local 192.168.222.4 port 53042 connected with 192.168.222.3 port 5001
[  7] local 192.168.222.4 port 53044 connected with 192.168.222.3 port 5001
[  8] local 192.168.222.4 port 53046 connected with 192.168.222.3 port 5001
[ 10] local 192.168.222.4 port 53048 connected with 192.168.222.3 port 5001
[ 11] local 192.168.222.4 port 53050 connected with 192.168.222.3 port 5001
[  9] local 192.168.222.4 port 53052 connected with 192.168.222.3 port 5001
[ ID] Interval       Transfer     Bandwidth
[ 10]  0.0-10.0 sec   204 MBytes   171 Mbits/sec
[  3]  0.0-10.0 sec   192 MBytes   161 Mbits/sec
[  6]  0.0-10.0 sec   222 MBytes   186 Mbits/sec
[ 11]  0.0-10.0 sec   519 MBytes   435 Mbits/sec
[  9]  0.0-10.0 sec   174 MBytes   146 Mbits/sec
[  5]  0.0-10.0 sec   344 MBytes   287 Mbits/sec
[ 12]  0.0-10.0 sec   329 MBytes   275 Mbits/sec
[  4]  0.0-10.0 sec   264 MBytes   221 Mbits/sec
[  8]  0.0-10.0 sec   215 MBytes   179 Mbits/sec
[  7]  0.0-10.1 sec   219 MBytes   182 Mbits/sec
[SUM]  0.0-10.1 sec  2.62 GBytes  2.24 Gbits/sec
[sander@sm1 go-p4pack]$ ]$ 
```

Because this system has a slower Xeon then my laptop 🙄 I also did the virtio to virtio test:
```
root@a9d1462ddec5:/go-p4pack# sudo ip netns exec host4 iperf -c 192.168.222.3 -P 10
------------------------------------------------------------
Client connecting to 192.168.222.3, TCP port 5001
TCP window size:  170 KByte (default)
------------------------------------------------------------
[ 11] local 192.168.222.4 port 47212 connected with 192.168.222.3 port 5001
[ 10] local 192.168.222.4 port 47204 connected with 192.168.222.3 port 5001
[  9] local 192.168.222.4 port 47208 connected with 192.168.222.3 port 5001
[ 12] local 192.168.222.4 port 47210 connected with 192.168.222.3 port 5001
[  3] local 192.168.222.4 port 47194 connected with 192.168.222.3 port 5001
[  5] local 192.168.222.4 port 47196 connected with 192.168.222.3 port 5001
[  8] local 192.168.222.4 port 47202 connected with 192.168.222.3 port 5001
[  7] local 192.168.222.4 port 47206 connected with 192.168.222.3 port 5001
[  6] local 192.168.222.4 port 47198 connected with 192.168.222.3 port 5001
[  4] local 192.168.222.4 port 47200 connected with 192.168.222.3 port 5001
[ ID] Interval       Transfer     Bandwidth
[  8]  0.0-10.0 sec   210 MBytes   177 Mbits/sec
[  7]  0.0-10.0 sec   190 MBytes   160 Mbits/sec
[  3]  0.0-10.0 sec   208 MBytes   174 Mbits/sec
[  5]  0.0-10.0 sec   222 MBytes   186 Mbits/sec
[  6]  0.0-10.0 sec   207 MBytes   173 Mbits/sec
[ 11]  0.0-10.0 sec   229 MBytes   191 Mbits/sec
[ 10]  0.0-10.0 sec   164 MBytes   137 Mbits/sec
[ 12]  0.0-10.0 sec   177 MBytes   148 Mbits/sec
[  9]  0.0-10.0 sec   220 MBytes   184 Mbits/sec
[  4]  0.0-10.1 sec   190 MBytes   159 Mbits/sec
[SUM]  0.0-10.1 sec  1.97 GBytes  1.68 Gbits/sec
```
As you can see this is 4x slower then the same test on my laptop (6.6 Gbit/s).... 😞

**Comment by swaroopsarma** [comment]
Issue resolved as part of this commit.
https://github.com/p4lang/p4-dpdk-target/pull/93
Thanks
