### ISSUE TITLE
Possible enhancement to bf_rt_table_attributes_impl.hpp

### ISSUE THREAD

**Issue by jfingerh** [p4lang/p4-dpdk-target#65]
After adding:

```
"#include <array>" to `src/bf_rt/bf_rt_common/bf_rt_table_attributes_impl.hpp`
```

the package now builds without issue.  Can you maybe try this to see if it will fix compilation issues for other people too?

@jamescchoi I see you on the commit log for this source file.  This comment is being passed on by me from someone else wanting to use this code commercially.

**Comment by swaroopsarma** [comment]
addresses in latest commit
