### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by AmitDavidi** [p4lang/p4-dpdk-target#83]
Hello, we're trying to build and install but we're experiencing a lot of errors,

we'll be more than happy to get a list of repositories we need to clone and build and prerequisites we need to install.
If there is a complete setup.sh somewhere it would be great.
thank you for your time :)

**Comment by jafingerhut** [comment]
I have an install script that seem to work for Ubuntu 22.04 and Fedora 34 that you can find in this PR: https://github.com/p4lang/p4-dpdk-target/pull/53

If you try it and it works for you, feel free to add a comment there asking if the maintainers of this repo can merge it in and mention it in the README.

**Comment by AmitDavidi** [comment]
@jafingerhut Hi, I wanted to ask, what should I have installed already on my machine (assuming a fresh 22.04 ubuntu installation) in order for the script to work properly? 
Currently I have only p4c installed.

**Comment by jfingerh** [comment]
I have successfully used that script with a freshly installed Ubuntu 22.04 system with nothing else installed.  I have NOT tested it on systems with p4c installed, but it might work.
