### ISSUE TITLE
P4runtime usage

### ISSUE THREAD

**Issue by khalidm96** [p4lang/p4-dpdk-target#97]
Hello, I want to use p4runtime with the P4-DPDK backend.

currently, I compiled the backend with the flag '--enable-grpc',
I also run the bf_switchd with '--p4rt-server' flag
I see that the grpc server started:
'bfruntime gRPC server started on 0.0.0.0:50052'

is there any documentation on how to connect to the server from the p4runtime client, enable the pipeline and add entries?

can I use the p4runtime shell (https://github.com/p4lang/p4runtime-shell) as a client? How can I do that?
I tried it, but it failed to connect to the server.

Thanks.

**Comment by jafingerhut** [comment]
I have recently documented a sequence of steps I took that installs the IPDK open source project, which I believe uses this project as one of several parts, and then connects to it via a simple P4Runtime API client program written in Python.  You can find the current version of my steps here: https://github.com/jafingerhut/p4-guide/blob/master/ipdk/23.01/README-install-ipdk-networking-container-ubuntu-20.04-and-test.md
